site_name: MPC Public Documentation Hub
site_url: https://docs.minorplanetcenter.net/
repo_url: https://github.com/Smithsonian/mpc-public

theme:
  name: material
  features:
#    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - search.highlight
    - search.suggest
  custom_dir: overrides

plugins:
  - search
  - mkdocs-jupyter:
      execute: false        # recommended for docs builds
      include_source: true  # optional: adds a source link / page.nb_url

nav:
  - Home: index.md
  - Topics of Interest:
      - Data & Services: data-services.md
      - Tutorials: tutorials.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
